### PR TITLE
Add french localization Chalos-Atiesh/GuildTradeskills

### PR DESCRIPTION
**Pull request by StephanDufour**
Based on german localization file

i'm not sure of these value:
    L['ONLINE'] = ONLINE
    L['OFFLINE'] = OFFLINE

 how could I test my file?

### CODE REVIEW

**Comment by luitzifa** [comment]
You need to add your file to the filelist in GuildTradeskills.toc 
The variable ONLINE and OFFLINE are defined locally in lines 13/14, so dont change line 321/322

**Comment by Chalos-Atiesh** [comment]
https://github.com/Chalos-Atiesh/GuildTradeskills/pull/58

**Comment by Chalos-Atiesh** [comment]
Thanks for adding this! It's much appreciated.

Please add this line to the GuildTradeskills.toc
Locale\localization.fr.lua

**Comment by StephanDufour** [comment]
Glad to help.

You also have https://www.deepl.com/fr/translator which gives good translation.
The translation is good but does it have to match Blizzard's?

**Comment by Chalos-Atiesh** [comment]
It uses Blizzard's translation to maintain whether friends and guildmates are online/offline without performing another character query so yes. It needs to match exactly.

I was doing some spot checking (just to make sure there were no curse words) and wasn't able to find a translation for 'Whou pinaise'. Could you update it to be a bit more formal?

**Comment by StephanDufour** [comment]
That's a "The Simpsons" easter egg in french.
I changed it to something more formal but it's a bit tricky because formal is not really used anymore and sounds a bit posh or silly, I think I found something neutral.

Where can I find the blizzard translation?
On my guild panel online members are seen as "En ligne" but offline just show the time since last login, for friends it shows "inconnu" ie "unknown".

Also note that I changed the first boolean of this line to false like for the german version:
local L = LibStub('AceLocale-3.0'):NewLocale(AddOnName, 'frFR', **false**, true)

I have added my caracters profession and looking for a member of my guild to make tests with me.

**Comment by Chalos-Atiesh** [comment]
Here's a list of global strings. It looks like they use:
`ERR_FRIEND_OFFLINE_S = "%s vient de se déconnecter.";`
`ERR_FRIEND_ONLINE_SS = "|Hplayer:%s|h[%s]|h vient de se connecter.";`
https://www.townlong-yak.com/framexml/34972/GlobalStrings.lua/FR

**Pull request merged**
